// src/app/fakeData.js

export const players = [
  {
    id: '1',
    name: 'TTV_Nitro',
    identifiers: ['steam:11000013abcdef0'],
    playtimeHours: 186,
    lastSeen: '2 hours ago',
    sessions30d: 24,
    infractions: 3,
    risk: 'High',
    status: 'Online',
    tags: ['Streamer', 'VIP'],
  },
  {
    id: '2',
    name: 'NovaRP',
    identifiers: ['steam:11000013aaaaaa0'],
    playtimeHours: 42,
    lastSeen: '1 day ago',
    sessions30d: 8,
    infractions: 0,
    risk: 'Low',
    status: 'Offline',
    tags: ['Police'],
  },
  {
    id: '3',
    name: 'DriftKing',
    identifiers: ['steam:11000013bbbbbbb'],
    playtimeHours: 73,
    lastSeen: '10 minutes ago',
    sessions30d: 15,
    infractions: 1,
    risk: 'Medium',
    status: 'Online',
    tags: ['Racer'],
  },
]
export const reports = [
  {
    id: 'r1',
    createdAt: '2025-11-24 21:13',
    reporter: 'NovaRP',
    accused: 'TTV_Nitro',
    reason: 'VDM / reckless driving in city center',
    status: 'Open',
    severity: 'High',
    handler: null,
  },
  {
    id: 'r2',
    createdAt: '2025-11-24 20:42',
    reporter: 'RandomCitizen',
    accused: 'DriftKing',
    reason: 'Street racing in safe zone',
    status: 'In progress',
    severity: 'Medium',
    handler: 'Lena',
  },
  {
    id: 'r3',
    createdAt: '2025-11-24 19:05',
    reporter: 'OfficerMike',
    accused: 'NovaRP',
    reason: 'Breaking RP in police station',
    status: 'Resolved',
    severity: 'Low',
    handler: 'Jay',
  },
]
